// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrwHnRXJijLC8dWgmfSt-aI_BQU6BEXJs',
    appId: '1:697309619297:web:7973ba768b7f5c4c913620',
    messagingSenderId: '697309619297',
    projectId: 'mycleancityapp-b7108',
    authDomain: 'mycleancityapp-b7108.firebaseapp.com',
    storageBucket: 'mycleancityapp-b7108.firebasestorage.app',
    measurementId: 'G-S3GDKP0122',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpZR9wVNy4hea0rlabqjCJXj8DO9gW0iQ',
    appId: '1:697309619297:android:ce14c7db573db743913620',
    messagingSenderId: '697309619297',
    projectId: 'mycleancityapp-b7108',
    storageBucket: 'mycleancityapp-b7108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9eJQsfza-O-STUR9g2ke0lCSMXr2NT60',
    appId: '1:697309619297:ios:02945aebfd1a3dfb913620',
    messagingSenderId: '697309619297',
    projectId: 'mycleancityapp-b7108',
    storageBucket: 'mycleancityapp-b7108.firebasestorage.app',
    iosBundleId: 'com.example.myCleanCityApp',
  );
}
